config/routes.rb
Medical::Application.routes.draw do

  namespace :ref do resources :death_reasons end

  namespace :ref do resources :sanatoria end

  namespace :ref do resources :lab_clin_mins end

  namespace :ref do resources :mkb_types end

  namespace :ref do resources :benefit_categories end

  resources :users

  namespace :ref do 
    resources :doctor_types 
    resources :ins_companies  
    resources :htm_help_types
    resources :med_diagnostic_test_types
    resources :hospitalization_types
    resources :diagnostic_test_types
    resources :lab_test_types       
  end

  namespace :rep do

    resource :main do
      member do
       get :ask_date
       post :report,:deads_by_deseases,:deads_by_ages,:death_reports,:invalids_report,:disp_invalids
      end  
    end

    resources :service, :only => [:edit,:create] 

  end

  root :to => 'welcome#index'  

  match 'csv' =>"clients#import_csv"

  match 'mse_calendar' =>"mse_calendar#show"
  match 'mse_events' =>"mse_calendar#events"

  resources :clients do
 
    member do
      get :operations,:search
    end 

      resources :sanatorium_notes

      resources :prof_inspections do

        resources :diagnoses
      end 

      resources :htm_help_notes
      resources :med_diagnostic_tests
      resources :hospitalizations
      resources :diagnostic_tests
      resources :lab_tests
      resources :benefits
      resources :mkbs
      resources :mses
      resources :disps
  end

  match 'ajax/clients' => "ajax#clients"
  match 'clients/:client_id/ajax/lab_test_form' => "ajax#lab_test_form"
  match 'ajax/mkb_types' => "ajax#mkb_types"
  match 'ajax/prof_inspections_by_year/clients/:client_id/year/:year' => "ajax#prof_inspections_by_year",:as => :prof_inspections_by_year
  match 'ajax/doctor_types' => "ajax#doctor_types"
  match 'ajax/lab_test_groups' => "ajax#lab_test_groups"
  match 'ajax/lab_test_types' => "ajax#lab_test_types"

end

app/models/diagnostic_test.rb
class DiagnosticTest < ActiveRecord::Base
 
  NORM = 1
  BETTER = 2
  WORSE = 3

  belongs_to :diagnostic_test_type, :class_name => 'Ref::DiagnosticTestType'
  validates :test_date,:diagnostic_test_type_id,:total, :presence => true
  belongs_to :client, :counter_cache => true

  scope :prof_inspection_minimum,lambda {prof_inspection_min} #Анализы для профосмотров

  scope :this_year,lambda {current_year} #Анализы за текущий год
  scope :in_year, lambda {|sd,ed| where("test_date between ? and ?",sd,ed)}
  
  scope :client_present,lambda {|e| joins(:client).merge(Client.present(e))}
  scope :client_sector,lambda {|n| joins(:client).merge(Client.sector(n))}
  scope :client_disabled,lambda { joins(:client).merge(Client.disables)}


  def self.current_year
    start_date=Time.now.beginning_of_year
    end_date=Time.now.end_of_year
    where("test_date between ? and ?",start_date,end_date)
  end

  def self.prof_inspection_min
    all.map {|dt| dt if dt.diagnostic_type_tag_list_include?(I18n.t(:prof_tag_name))}.compact
  end

  def diagnostic_type_tag_list_include?(tag_name)
    diagnostic_test_type.tag_list.include?(tag_name) if diagnostic_test_type and diagnostic_test_type.tag_list
  end

 def valid_test?
    test_date+diagnostic_test_type.valid_period >= Date.parse(Time.now.to_s)
 end

  def total_info
   result=case total
           when NORM then I18n.t(:diagnostic_test_norm)
           when BETTER then I18n.t(:diagnostic_test_better)
           when WORSE then I18n.t(:diagnostic_test_worse)
          end 
   result
  end

  



end
# == Schema Information
#
# Table name: diagnostic_tests
#
#  id                      :integer         not null, primary key
#  test_date               :date
#  diagnostic_test_type_id :integer
#  client_id               :integer
#  result                  :text
#  created_at              :datetime
#  updated_at              :datetime
#

app/models/ref/diagnostic_test_type.rb
class Ref::DiagnosticTestType < ActiveRecord::Base
  validates :name,:presence => true
  has_many :diagnostic_tests 

  acts_as_taggable #Теги 
  scope :prof_inspection_minimum,lambda {prof_inspection_min} #Анализы для профосмотров


def can_be_deleted
  diagnostic_tests.count<=0
end

 def self.prof_inspection_min
   all.map {|dtt| dtt if dtt.tag_list and dtt.tag_list.include?(I18n.t(:prof_tag_name))}.compact 
 end

 


end
# == Schema Information
#
# Table name: ref_diagnostic_test_types
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  valid_period :integer
#

app/controllers/diagnostic_tests_controller.rb
class DiagnosticTestsController < ApplicationController
  # GET /diagnostic_tests
  # GET /diagnostic_tests.json
  before_filter :find_client

  def find_client
    @client=Client.find(params[:client_id])
  end

  def index
    @diagnostic_tests = @client.diagnostic_tests.page(params[:page]).per(10)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnostic_tests }
    end
  end

  # GET /diagnostic_tests/1
  # GET /diagnostic_tests/1.json
  def show
    @diagnostic_test = DiagnosticTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnostic_test }
    end
  end

  # GET /diagnostic_tests/new
  # GET /diagnostic_tests/new.json
  def new
    @diagnostic_test = DiagnosticTest.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnostic_test }
    end
  end

  # GET /diagnostic_tests/1/edit
  def edit
    @diagnostic_test = DiagnosticTest.find(params[:id])
  end

  # POST /diagnostic_tests
  # POST /diagnostic_tests.json
  def create
    @diagnostic_test = DiagnosticTest.new(params[:diagnostic_test])
    @diagnostic_test.client=@client

    respond_to do |format|
      if @diagnostic_test.save
        format.html { redirect_to client_diagnostic_tests_path(@client), notice: I18n.t(:record_saved) }
        format.json { render json: @diagnostic_test, status: :created, location: @diagnostic_test }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnostic_tests/1
  # PUT /diagnostic_tests/1.json
  def update
    @diagnostic_test = DiagnosticTest.find(params[:id])

    respond_to do |format|
      if @diagnostic_test.update_attributes(params[:diagnostic_test])
        format.html { redirect_to client_diagnostic_tests_path(@client), notice: I18n.t(:record_updated)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_tests/1
  # DELETE /diagnostic_tests/1.json
  def destroy
    @diagnostic_test = DiagnosticTest.find(params[:id])
    @diagnostic_test.destroy

    respond_to do |format|
      format.html { redirect_to client_diagnostic_tests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/diagnostic_tests_helper.rb
module DiagnosticTestsHelper
end

app/views/diagnostic_tests/_diagnostic_test.html.haml
%p
  ="#{l item.test_date} | #{item.diagnostic_test_type.name}: #{item.result}"

app/views/diagnostic_tests/_form.html.haml
=bootstrap_form_for [@client, @diagnostic_test] do |f|
  %fieldset
    %legend 
      Общие данные
    =f.date_select :test_date,:label => "Дата"
    =f.collection_select :diagnostic_test_type_id,Ref::DiagnosticTestType.all,:id,:name,:label => "Тип анализа"
  %fieldset
    %legend 
      Результат
    =f.radio_button :total,DiagnosticTest::NORM,:label => "Норма"
    =f.radio_button :total,DiagnosticTest::BETTER ,:label => "Без улучшения"
    =f.radio_button :total,DiagnosticTest::WORSE,:label => "Ухудшение. Контроль"
  %fieldset
    %legend 
      Комментарий
    =f.text_field :result, :label => ""
  
  .form-actions
    =f.submit "Сохранить",:class => "btn primary"

app/views/diagnostic_tests/edit.html.haml
%h1 Редактирование диагностического исследования

= render 'form'

= link_to 'Назад', client_diagnostic_tests_path(@client)

app/views/diagnostic_tests/index.html.haml
- present "ClientOperations" do |p|

  -p.prepare(@diagnostic_tests,"Диагностические исследования",notice,@client)

  =p.client_header

  =p.table_or_empty do
    %table{:class => "table table-bordered table-striped"}
      %tr
        %th Дата
        %th Тип исследования
        %th Результат
        %th Комментарий
        %th
        %th

      - @diagnostic_tests.each do |diagnostic_test|
        %tr
          %td= l diagnostic_test.test_date
          %td= diagnostic_test.diagnostic_test_type.name
          %td= diagnostic_test.total_info 
          %td= diagnostic_test.result
                
          %td= link_to content_tag(:span,"",class: "ui-icon ui-icon-pencil"),edit_client_diagnostic_test_path(@client,diagnostic_test)
          %td= link_to content_tag(:span,"",class: "ui-icon ui-icon-minus") , client_diagnostic_test_path(@client,diagnostic_test), :confirm => 'Are you sure?', :method => :delete
  %br

  = link_to t(:new_record), new_client_diagnostic_test_path(@client)

app/views/diagnostic_tests/new.html.haml
%h1 Новое диагностическое исследование

= render 'form'

= link_to 'Назад', client_diagnostic_tests_path(@client)

app/views/diagnostic_tests/show.html.haml
%p#notice= notice

%p
  %b Test date:
  = @diagnostic_test.test_date
%p
  %b Diagnostic test type:
  = @diagnostic_test.diagnostic_test_type
%p
  %b Result:
  = @diagnostic_test.result
%p
  %b Client:
  = @diagnostic_test.client_id

= link_to 'Edit', edit_diagnostic_test_path(@diagnostic_test)
\|
= link_to 'Back', diagnostic_tests_path