config/routes.rb
Medical::Application.routes.draw do

  namespace :ref do resources :death_reasons end

  namespace :ref do resources :sanatoria end

  namespace :ref do resources :lab_clin_mins end

  namespace :ref do resources :mkb_types end

  namespace :ref do resources :benefit_categories end

  resources :users

  namespace :ref do 
    resources :doctor_types 
    resources :ins_companies  
    resources :htm_help_types
    resources :med_diagnostic_test_types
    resources :hospitalization_types
    resources :diagnostic_test_types
    resources :lab_test_types       
  end

  namespace :rep do

    resource :main do
      member do
       get :ask_date
       post :report,:deads_by_deseases,:deads_by_ages,:death_reports,:invalids_report,:disp_invalids
      end  
    end

    resources :service, :only => [:edit,:create] 

  end

  root :to => 'welcome#index'  

  match 'csv' =>"clients#import_csv"

  match 'mse_calendar' =>"mse_calendar#show"
  match 'mse_events' =>"mse_calendar#events"

  resources :clients do
 
    member do
      get :operations,:search
    end 

      resources :sanatorium_notes

      resources :prof_inspections do

        resources :diagnoses
      end 

      resources :htm_help_notes
      resources :med_diagnostic_tests
      resources :hospitalizations
      resources :diagnostic_tests
      resources :lab_tests
      resources :benefits
      resources :mkbs
      resources :mses
      resources :disps
  end

  match 'ajax/clients' => "ajax#clients"
  match 'clients/:client_id/ajax/lab_test_form' => "ajax#lab_test_form"
  match 'ajax/mkb_types' => "ajax#mkb_types"
  match 'ajax/prof_inspections_by_year/clients/:client_id/year/:year' => "ajax#prof_inspections_by_year",:as => :prof_inspections_by_year
  match 'ajax/doctor_types' => "ajax#doctor_types"
  match 'ajax/lab_test_groups' => "ajax#lab_test_groups"
  match 'ajax/lab_test_types' => "ajax#lab_test_types"

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  # GET /diagnoses
  # GET /diagnoses.json

  before_filter :find_prof_inspection

  def find_prof_inspection
    @prof_inspection=ProfInspection.find(params[:prof_inspection_id])
  end


  def index
    @diagnoses = @prof_inspection.diagnosis

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnoses }
    end
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
    @diagnosis = Diagnosis.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnosis }
    end
  end

  # GET /diagnoses/new
  # GET /diagnoses/new.json
  def new
    @diagnosis = Diagnosis.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnosis }
    end
  end

  # GET /diagnoses/1/edit
  def edit
    @diagnosis = Diagnosis.find(params[:id])
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @diagnosis = Diagnosis.new(params[:diagnosis])
    @diagnosis.prof_inspection_id = @prof_inspection.id

    respond_to do |format|
      if @diagnosis.save
        format.html { redirect_to client_prof_inspections_path(@prof_inspection.client), notice: I18n.t(:record_created) }
        format.json { render json: @diagnosis, status: :created, location: @diagnosis }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnoses/1
  # PUT /diagnoses/1.json
  def update
    @diagnosis = Diagnosis.find(params[:id])

    respond_to do |format|
      if @diagnosis.update_attributes(params[:diagnosis])
        format.html { redirect_to client_prof_inspections_path(@prof_inspection.client), notice: I18n.t(:record_updated) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
    @diagnosis = Diagnosis.find(params[:id])
    @id = @diagnosis.id
    @diagnosis.destroy

    respond_to do |format|
      format.html { redirect_to client_prof_inspections_path(@prof_inspection.client)}
      format.json { head :ok }
      format.js 
    end
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper



def ddd

bar
bax

b

end

end

app/views/diagnoses/_form.html.haml
=bootstrap_form_for [@prof_inspection.client,@prof_inspection,@diagnosis] do |f|
  =f.check_box :first_detected,:label => "Выявлено впервые"
  =f.check_box :stat_card,:label => "Стат. талон выдан ?"
  =f.text_field :mkb,:label => "Заболевание",:class => "span6 mkb"
  .form-actions
    =f.submit "Сохранить",:class => "btn primary"

app/views/diagnoses/edit.html.haml
%h1 Редактировать диагноз

= render 'form'

= link_to 'Назад', client_prof_inspections_path(@prof_inspection.client_id)

app/views/diagnoses/index.html.haml
%h1 Listing diagnoses

%table
  %tr
    %th Prof inspection
    %th Mkb type
    %th First detected
    %th
    %th
    %th

  - @diagnoses.each do |diagnosis|
    %tr
      %td= diagnosis.prof_inspection_id
      %td= diagnosis.mkb_type_id
      %td= diagnosis.first_detected
      %td= link_to 'Show', diagnosis
      %td= link_to 'Edit', edit_client_prof_inspection_diagnosis_path(@prof_inspection.client,@prof_inspection,diagnosis)
      %td= link_to 'Destroy', client_prof_inspection_diagnosis_path(@prof_inspection.client,@prof_inspection,diagnosis), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Diagnosis', new_client_prof_inspection_diagnosis_path(@prof_inspection.client,@prof_inspection)

app/views/diagnoses/new.html.haml
%h1 Новый диагноз

= render 'form'

= link_to 'Назад', client_prof_inspection_diagnoses_path

app/views/diagnoses/show.html.haml
%p#notice= notice

%p
  %b Prof inspection:
  = @diagnosis.prof_inspection_id
%p
  %b Mkb type:
  = @diagnosis.mkb_type_id
%p
  %b First detected:
  = @diagnosis.first_detected

= link_to 'Edit', edit_diagnosis_path(@diagnosis)
\|
= link_to 'Back', diagnoses_path